import { GSI1_NAME, METRICS_NAMESPACE, SERVICE_NAME, type TargetEnv } from '@roofing-crm/shared';
import * as cdk from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as sns from 'aws-cdk-lib/aws-sns';
import type { Construct } from 'constructs';
import { AsyncObservableFunction } from './constructs/async-observable-function';

export interface CoreStackProps extends cdk.StackProps {
  targetEnv: TargetEnv;
}

/**
 * Stateful and cross-cutting resources: the single DynamoDB table, the one operations
 * topic every alarm fans out through, the PagerDuty routing-key secret, and the alert
 * notifier that every critical failure path in this service routes to.
 */
export class CoreStack extends cdk.Stack {
  readonly table: dynamodb.TableV2;
  readonly operationsTopic: sns.Topic;
  readonly pagerDutySecret: secretsmanager.Secret;
  readonly alertNotifier: AsyncObservableFunction;

  constructor(scope: Construct, id: string, props: CoreStackProps) {
    super(scope, id, props);

    this.table = new dynamodb.TableV2(this, 'Table', {
      partitionKey: { name: 'PK', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'SK', type: dynamodb.AttributeType.STRING },
      billing: dynamodb.Billing.onDemand(),
      globalSecondaryIndexes: [
        {
          indexName: GSI1_NAME,
          partitionKey: { name: 'GSI1PK', type: dynamodb.AttributeType.STRING },
          sortKey: { name: 'GSI1SK', type: dynamodb.AttributeType.STRING },
          projectionType: dynamodb.ProjectionType.ALL,
        },
      ],
      pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    this.operationsTopic = new sns.Topic(this, 'OperationsTopic', {
      topicName: `${SERVICE_NAME}-${props.targetEnv}-operations`,
      displayName: `${SERVICE_NAME} operations alerts`,
    });

    /**
     * Stub secret. The value is generated by Secrets Manager rather than written into
     * the template, so no routing key — real or placeholder — is ever committed. An
     * operator replaces `routingKey` with the real PagerDuty integration key.
     */
    this.pagerDutySecret = new secretsmanager.Secret(this, 'PagerDutyRoutingKey', {
      // Named so the operator who has to paste the real key in can find it, and so the
      // IAM grant that scopes the notifier to this one ARN is auditable by eye.
      secretName: `${SERVICE_NAME}/${props.targetEnv}/pagerduty-routing-key`,
      description: `PagerDuty Events API v2 routing key for ${SERVICE_NAME}`,
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: 'routingKey',
        excludePunctuation: true,
        passwordLength: 32,
      },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    this.alertNotifier = new AsyncObservableFunction(this, 'AlertNotifier', {
      entry: 'src/pagerduty/notifier.ts',
      description: `${SERVICE_NAME} PagerDuty alert notifier`,
      serviceName: SERVICE_NAME,
      metricsNamespace: METRICS_NAMESPACE,
      targetEnv: props.targetEnv,
      alarmTopic: this.operationsTopic,
      alarmName: `${SERVICE_NAME}-${props.targetEnv}-alert-notifier-dlq-not-empty`,
      memorySize: 256,
      timeout: cdk.Duration.seconds(15),
      environment: {
        PAGERDUTY_SECRET_ARN: this.pagerDutySecret.secretArn,
        PAGERDUTY_ENABLED: String(props.targetEnv === 'prod'),
      },
    });

    this.pagerDutySecret.grantRead(this.alertNotifier.handler);

    new cdk.CfnOutput(this, 'TableName', { value: this.table.tableName });
    new cdk.CfnOutput(this, 'OperationsTopicArn', { value: this.operationsTopic.topicArn });
    new cdk.CfnOutput(this, 'PagerDutySecretArn', { value: this.pagerDutySecret.secretArn });
  }
}
