import { SERVICE_NAME } from '@roofing-crm/shared';
import * as cdk from 'aws-cdk-lib';
import { Match, Template } from 'aws-cdk-lib/assertions';
import { beforeAll, describe, expect, it } from 'vitest';
import { ApiStack, DATA_BUCKET_NAME, NLQ_MODEL_ID } from './api-stack';
import { CoreStack } from './core-stack';

const env = { account: '795366345505', region: 'us-east-2' };
const tags = { project_name: SERVICE_NAME, environment: 'dev' };

let coreTemplate: Template;
let apiTemplate: Template;

/**
 * Synthesis bundles both Lambdas with esbuild. That is ~200ms warm but well over Vitest's
 * default 10s hook budget on a cold esbuild cache, so the timeout is raised to keep a clean
 * checkout from failing the suite for a reason that has nothing to do with the templates.
 */
beforeAll(() => {
  const app = new cdk.App();
  const core = new CoreStack(app, 'TestCore', { env, tags, targetEnv: 'dev' });
  const api = new ApiStack(app, 'TestApi', { env, tags, targetEnv: 'dev', table: core.table });
  coreTemplate = Template.fromStack(core);
  apiTemplate = Template.fromStack(api);
}, 120_000);

describe('every Lambda carries the observability contract', () => {
  it('enables X-Ray active tracing and source maps', () => {
    for (const template of [coreTemplate, apiTemplate]) {
      const functions = template.findResources('AWS::Lambda::Function');
      const appFunctions = Object.values(functions).filter(
        (fn) => fn.Properties?.Environment?.Variables?.POWERTOOLS_SERVICE_NAME !== undefined,
      );
      expect(appFunctions.length).toBeGreaterThan(0);
      for (const fn of appFunctions) {
        expect(fn.Properties.TracingConfig).toEqual({ Mode: 'Active' });
        expect(fn.Properties.Environment.Variables.NODE_OPTIONS).toBe('--enable-source-maps');
        expect(fn.Properties.Environment.Variables.POWERTOOLS_SERVICE_NAME).toBe(SERVICE_NAME);
        expect(fn.Properties.Environment.Variables.POWERTOOLS_METRICS_NAMESPACE).toBe('RoofingCrm');
      }
    }
  });

  it('gives each function a distinct conventionally named log group', () => {
    const names = [coreTemplate, apiTemplate].flatMap((template) =>
      Object.values(template.findResources('AWS::Logs::LogGroup')).map(
        (group) => group.Properties.LogGroupName as string,
      ),
    );
    expect(names.length).toBeGreaterThan(0);
    for (const name of names) {
      expect(name).toMatch(new RegExp(`^/aws/lambda/${SERVICE_NAME}-dev-`));
    }
    // Two wrapper constructs both name their inner function `Function`, so an id-only
    // log-group name would collide and fail the deploy.
    expect(new Set(names).size).toBe(names.length);
  });
});

describe('the async alert notifier has a DLQ with one self-resolving alarm', () => {
  it('routes async failures to an SQS dead-letter queue', () => {
    coreTemplate.hasResourceProperties('AWS::Lambda::Function', {
      DeadLetterConfig: { TargetArn: Match.anyValue() },
    });
    coreTemplate.resourceCountIs('AWS::SQS::Queue', 1);
  });

  it('alarms on queue depth greater than zero and clears itself on drain', () => {
    coreTemplate.hasResourceProperties('AWS::CloudWatch::Alarm', {
      MetricName: 'ApproximateNumberOfMessagesVisible',
      Namespace: 'AWS/SQS',
      Statistic: 'Maximum',
      Threshold: 0,
      ComparisonOperator: 'GreaterThanThreshold',
      EvaluationPeriods: 1,
      DatapointsToAlarm: 1,
      TreatMissingData: 'notBreaching',
      AlarmActions: Match.anyValue(),
      OKActions: Match.anyValue(),
    });
    coreTemplate.resourceCountIs('AWS::CloudWatch::Alarm', 1);
  });

  it('points both alarm transitions at the single operations topic', () => {
    const alarms = coreTemplate.findResources('AWS::CloudWatch::Alarm');
    const alarm = Object.values(alarms)[0];
    expect(alarm?.Properties.AlarmActions).toEqual(alarm?.Properties.OKActions);
  });
});

describe('PagerDuty routing key', () => {
  it('is generated by Secrets Manager rather than written into the template', () => {
    coreTemplate.hasResourceProperties('AWS::SecretsManager::Secret', {
      GenerateSecretString: Match.objectLike({ GenerateStringKey: 'routingKey' }),
    });

    const secrets = Object.values(coreTemplate.findResources('AWS::SecretsManager::Secret'));
    expect(secrets).toHaveLength(1);
    expect(secrets[0]?.Properties.SecretString).toBeUndefined();
  });

  it('grants the notifier read access scoped to that one secret ARN', () => {
    coreTemplate.hasResourceProperties('AWS::IAM::Policy', {
      PolicyDocument: Match.objectLike({
        Statement: Match.arrayWith([
          Match.objectLike({
            Action: Match.arrayWith(['secretsmanager:GetSecretValue']),
            Resource: { Ref: Match.stringLikeRegexp('PagerDutyRoutingKey') },
          }),
        ]),
      }),
    });
  });
});

describe('the tRPC API', () => {
  it('is fronted by an API Gateway HTTP API, not a Lambda function URL', () => {
    apiTemplate.resourceCountIs('AWS::ApiGatewayV2::Api', 1);
    apiTemplate.resourceCountIs('AWS::Lambda::Url', 0);
    apiTemplate.hasResourceProperties('AWS::ApiGatewayV2::Route', {
      RouteKey: 'ANY /trpc/{proxy+}',
    });
  });

  /**
   * The natural-language panel renders a disabled state when no model is configured, so a
   * deploy that forgot this variable would look like a working site with a dead feature
   * rather than like a failure.
   */
  it('configures the natural-language model and grants invoke on it', () => {
    apiTemplate.hasResourceProperties('AWS::Lambda::Function', {
      Environment: { Variables: Match.objectLike({ NLQ_MODEL_ID }) },
    });

    apiTemplate.hasResourceProperties('AWS::IAM::Policy', {
      PolicyDocument: Match.objectLike({
        Statement: Match.arrayWith([
          Match.objectLike({
            Action: 'bedrock:InvokeModel',
            Resource: Match.arrayWith([Match.stringLikeRegexp('foundation-model')]),
          }),
        ]),
      }),
    });
  });

  /**
   * Pinned as a literal so that changing the model is a deliberate edit in two places. Claude 3
   * Haiku is called out by name because it is the plausible wrong answer: it reads like a
   * cheaper Haiku, and it is denied on this account.
   */
  it('pins the model to Claude Haiku 4.5', () => {
    expect(NLQ_MODEL_ID).toBe('us.anthropic.claude-haiku-4-5-20251001-v1:0');
    expect(NLQ_MODEL_ID).not.toBe('us.anthropic.claude-3-haiku-20240307-v1:0');
  });

  /**
   * A cross-region inference profile invokes the model in whichever region it routes to, so
   * pinning the region here would fail at request time — after a green deploy — rather than in
   * this test.
   */
  it('leaves the region open on the foundation-model grant', () => {
    apiTemplate.hasResourceProperties('AWS::IAM::Policy', {
      PolicyDocument: Match.objectLike({
        Statement: Match.arrayWith([
          Match.objectLike({
            Action: 'bedrock:InvokeModel',
            Resource: Match.arrayWith([
              'arn:aws:bedrock:*::foundation-model/anthropic.claude-haiku-4-5-20251001-v1:0',
            ]),
          }),
        ]),
      }),
    });
  });

  /** No key means no key to leak: authentication is the execution role, not an env var. */
  it('holds no model API key in the template', () => {
    const rendered = JSON.stringify(apiTemplate.toJSON());
    expect(rendered).not.toMatch(/OPENAI_API_KEY|ANTHROPIC_API_KEY|AWS_BEARER_TOKEN_BEDROCK/);
  });
});

/**
 * The CRM serves the county's parcels by reading the pipeline's published Parquet, and the IAM
 * grant is what makes "through the published interface" true rather than aspirational. These
 * assertions are about the boundary, not about plumbing: a grant that widened to the whole
 * bucket would let a later change read the pipeline's internals and still pass every other test.
 */
describe('the published parcel snapshot', () => {
  it('tells the handler which bucket to read', () => {
    apiTemplate.hasResourceProperties('AWS::Lambda::Function', {
      Environment: { Variables: Match.objectLike({ DATA_BUCKET_NAME }) },
    });
  });

  it('grants read only under publish/, and never write', () => {
    apiTemplate.hasResourceProperties('AWS::IAM::Policy', {
      PolicyDocument: Match.objectLike({
        Statement: Match.arrayWith([
          Match.objectLike({
            Action: 's3:GetObject',
            Resource: `arn:aws:s3:::${DATA_BUCKET_NAME}/publish/*`,
          }),
        ]),
      }),
    });

    const rendered = JSON.stringify(apiTemplate.toJSON());
    expect(rendered).not.toMatch(/s3:PutObject|s3:DeleteObject/);
    expect(rendered).not.toMatch(new RegExp(`${DATA_BUCKET_NAME}/(raw|staged|internal)`));
  });

  /**
   * Listing cannot be scoped by resource ARN — the resource is the bucket itself — so the
   * prefix condition is the only thing standing between "list the published snapshot" and
   * "enumerate the pipeline's internals".
   */
  it('constrains listing to the published prefix', () => {
    apiTemplate.hasResourceProperties('AWS::IAM::Policy', {
      PolicyDocument: Match.objectLike({
        Statement: Match.arrayWith([
          Match.objectLike({
            Action: 's3:ListBucket',
            Resource: `arn:aws:s3:::${DATA_BUCKET_NAME}`,
            Condition: { StringLike: { 's3:prefix': ['publish/*'] } },
          }),
        ]),
      }),
    });
  });

  /**
   * Transposing 181,218 parcels into typed arrays is CPU-bound, and Lambda scales vCPU with
   * memory, so this number is a latency setting. Dropping it would not fail a deploy; it would
   * show up as a slow first search.
   */
  it('gives the handler enough CPU to load the snapshot on a cold start', () => {
    apiTemplate.hasResourceProperties('AWS::Lambda::Function', {
      MemorySize: 2048,
      Timeout: 30,
    });
  });
});
