import { SERVICE_NAME } from '@roofing-crm/shared';
import * as cdk from 'aws-cdk-lib';
import { Match, Template } from 'aws-cdk-lib/assertions';
import { beforeAll, describe, expect, it } from 'vitest';
import { ApiStack } from './api-stack';
import { CoreStack } from './core-stack';

const env = { account: '795366345505', region: 'us-east-2' };
const tags = { project_name: SERVICE_NAME, environment: 'dev' };

let coreTemplate: Template;
let apiTemplate: Template;

beforeAll(() => {
  const app = new cdk.App();
  const core = new CoreStack(app, 'TestCore', { env, tags, targetEnv: 'dev' });
  const api = new ApiStack(app, 'TestApi', { env, tags, targetEnv: 'dev', table: core.table });
  coreTemplate = Template.fromStack(core);
  apiTemplate = Template.fromStack(api);
});

describe('every Lambda carries the observability contract', () => {
  it('enables X-Ray active tracing and source maps', () => {
    for (const template of [coreTemplate, apiTemplate]) {
      const functions = template.findResources('AWS::Lambda::Function');
      const appFunctions = Object.values(functions).filter(
        (fn) => fn.Properties?.Environment?.Variables?.POWERTOOLS_SERVICE_NAME !== undefined,
      );
      expect(appFunctions.length).toBeGreaterThan(0);
      for (const fn of appFunctions) {
        expect(fn.Properties.TracingConfig).toEqual({ Mode: 'Active' });
        expect(fn.Properties.Environment.Variables.NODE_OPTIONS).toBe('--enable-source-maps');
        expect(fn.Properties.Environment.Variables.POWERTOOLS_SERVICE_NAME).toBe(SERVICE_NAME);
        expect(fn.Properties.Environment.Variables.POWERTOOLS_METRICS_NAMESPACE).toBe('RoofingCrm');
      }
    }
  });
});

describe('the async alert notifier has a DLQ with one self-resolving alarm', () => {
  it('routes async failures to an SQS dead-letter queue', () => {
    coreTemplate.hasResourceProperties('AWS::Lambda::Function', {
      DeadLetterConfig: { TargetArn: Match.anyValue() },
    });
    coreTemplate.resourceCountIs('AWS::SQS::Queue', 1);
  });

  it('alarms on queue depth greater than zero and clears itself on drain', () => {
    coreTemplate.hasResourceProperties('AWS::CloudWatch::Alarm', {
      MetricName: 'ApproximateNumberOfMessagesVisible',
      Namespace: 'AWS/SQS',
      Statistic: 'Maximum',
      Threshold: 0,
      ComparisonOperator: 'GreaterThanThreshold',
      EvaluationPeriods: 1,
      DatapointsToAlarm: 1,
      TreatMissingData: 'notBreaching',
      AlarmActions: Match.anyValue(),
      OKActions: Match.anyValue(),
    });
    coreTemplate.resourceCountIs('AWS::CloudWatch::Alarm', 1);
  });

  it('points both alarm transitions at the single operations topic', () => {
    const alarms = coreTemplate.findResources('AWS::CloudWatch::Alarm');
    const alarm = Object.values(alarms)[0];
    expect(alarm?.Properties.AlarmActions).toEqual(alarm?.Properties.OKActions);
  });
});

describe('PagerDuty routing key', () => {
  it('is generated by Secrets Manager rather than written into the template', () => {
    coreTemplate.hasResourceProperties('AWS::SecretsManager::Secret', {
      GenerateSecretString: Match.objectLike({ GenerateStringKey: 'routingKey' }),
    });

    const secrets = Object.values(coreTemplate.findResources('AWS::SecretsManager::Secret'));
    expect(secrets).toHaveLength(1);
    expect(secrets[0]?.Properties.SecretString).toBeUndefined();
  });

  it('grants the notifier read access scoped to that one secret ARN', () => {
    coreTemplate.hasResourceProperties('AWS::IAM::Policy', {
      PolicyDocument: Match.objectLike({
        Statement: Match.arrayWith([
          Match.objectLike({
            Action: Match.arrayWith(['secretsmanager:GetSecretValue']),
            Resource: { Ref: Match.stringLikeRegexp('PagerDutyRoutingKey') },
          }),
        ]),
      }),
    });
  });
});

describe('the tRPC API', () => {
  it('is fronted by an API Gateway HTTP API, not a Lambda function URL', () => {
    apiTemplate.resourceCountIs('AWS::ApiGatewayV2::Api', 1);
    apiTemplate.resourceCountIs('AWS::Lambda::Url', 0);
    apiTemplate.hasResourceProperties('AWS::ApiGatewayV2::Route', {
      RouteKey: 'ANY /trpc/{proxy+}',
    });
  });
});
